[package]
name = "sqlx-ydb-migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
ydb-sqlx = { path = "../ydb-sqlx" }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls"] }
tokio = { version = "1.22", features = ["full"] }
tracing-subscriber = "0.3"
dotenv = "0.15"
